apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cb-test-api
  namespace: prd-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cb-test-api
    spec:
      containers:
      - image: 262213740647.dkr.ecr.ap-northeast-2.amazonaws.com/k5s_ecr:v21
        imagePullPolicy: Always
        name: cb-test-api
        ports:
        - containerPort: 8080
